name: "Release"

on:
  push:
    tags:
      - "*.*.*"
env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  SOURCE_DIRECTORY: ${{ github.workspace }}
  SOLUTION_FILE: "OLT.Extensions.Configuration.Infisical.sln"
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Get Version
        id: get_version
        uses: tj-actions/branch-names@v8
        with: 
          strip_tag_prefix: ''

      - name: Restore dependencies
        run: dotnet restore ${{ format('{0}/{1}', env.SOURCE_DIRECTORY, env.SOLUTION_FILE) }}

      - name: Build
        run: dotnet build ${{ format('{0}/{1}', env.SOURCE_DIRECTORY, env.SOLUTION_FILE) }} --configuration Release -p:Version=${{ steps.get_version.outputs.tag }} --no-restore

      - name: "Pack project"
        run: dotnet pack ${{ format('{0}/{1}', env.SOURCE_DIRECTORY, env.SOLUTION_FILE) }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.get_version.outputs.tag }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/**/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
